# Generated by Django 5.0.3 on 2024-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_category_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images', verbose_name='Фото'),
        ),
    ]
